name: Build Docker image
on:
  push:
    branches:
      - master
jobs:
  push_to_ghcr:
    name: Push to ghcr.io
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish
        uses: docker/build-push-action@v2
        with:
          tags: ${{ format('ghcr.io/{0}/ttt_server:latest', github.actor) }}
          push: true
  # push_to_dockerhub:
  #   name: Push to Dockerhub
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout repo
  #       uses: actions/checkout@v2
  #     - name: Login to GitHub Container Registry
  #       uses: docker/login-action@v1
  #       with:
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_TOKEN }}
  #     - name: Publish
  #       uses: docker/build-push-action@v2
  #       with:
  #         tags: ${{ format('{0}/ttt_server:latest', secrets.DOCKERHUB_USERNAME) }}
  #         push: true
